In [115]:
import cv2
img = cv2.imread("images/RGBY.jpg")

In [116]:
print(img.shape)

(586, 415, 3)


In [117]:
print(img)

[[[ 38   3   0]
  [ 70  12   7]
  [ 96   0   0]
  ...
  [  0  20  21]
  [  0  20  21]
  [  0  20  21]]

 [[ 65   6   4]
  [112  29  27]
  [152  22  22]
  ...
  [118 238 237]
  [118 239 235]
  [118 238 237]]

 [[101   0   0]
  [160  30  30]
  [208  29  30]
  ...
  [ 54 246 239]
  [ 54 247 237]
  [ 54 246 239]]

 ...

 [[  0  55   0]
  [ 57 163  56]
  [ 35 193  27]
  ...
  [ 16   6 250]
  [ 16   6 250]
  [ 16   6 250]]

 [[  0  55   0]
  [ 57 163  56]
  [ 35 193  27]
  ...
  [ 16   6 250]
  [ 16   6 250]
  [ 16   6 250]]

 [[  0  55   0]
  [ 57 163  56]
  [ 35 193  27]
  ...
  [ 16   6 250]
  [ 16   6 250]
  [ 16   6 250]]]


In [118]:
img = cv2.imread("images/RGBY.jpg",1)

In [119]:
print(img.shape)

(586, 415, 3)


In [120]:
print("Top left",img[0,0])

Top left [38  3  0]


In [121]:
print(img.dtype)

uint8


In [122]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [123]:
img1 = cv2.imread("images/Alpha.jpg");

In [124]:
# img1 = img1.convert("L")
from PIL import Image

In [125]:
img2 = Image.open("images/Alpha.jpg")

In [126]:
img2 = img2.convert("L")

In [127]:
img2.show()

In [128]:
# imgplot = plt.imshow(img)

In [129]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [130]:
img2 = cv2.imread("images/Alpha.jpg")

In [131]:
blur = cv2.GaussianBlur(img2,(5,5),0)

In [132]:
# blur.show()
print(blur)

[[[ 78  84  91]
  [ 80  86  93]
  [ 87  93  97]
  ...
  [ 17  23  32]
  [ 18  23  32]
  [ 19  23  32]]

 [[ 76  82  90]
  [ 78  84  91]
  [ 84  91  95]
  ...
  [ 16  23  32]
  [ 18  23  32]
  [ 19  23  32]]

 [[ 72  79  86]
  [ 73  80  87]
  [ 78  86  91]
  ...
  [ 16  23  32]
  [ 18  23  31]
  [ 18  24  31]]

 ...

 [[ 97 162 191]
  [ 96 161 191]
  [ 95 160 190]
  ...
  [ 22  23  24]
  [ 23  23  25]
  [ 24  23  25]]

 [[ 97 161 188]
  [ 96 161 188]
  [ 95 160 187]
  ...
  [ 22  22  23]
  [ 23  22  24]
  [ 23  22  24]]

 [[ 97 161 187]
  [ 96 161 187]
  [ 95 160 186]
  ...
  [ 22  21  23]
  [ 23  22  24]
  [ 23  22  24]]]
